# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.x
- 1.7.x
services:
  - docker
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE: small
  - SNAP_VERSION: latest
    OS: alpine
    TEST_TYPE: large
  - SNAP_VERSION: latest_build
    OS: alpine
    TEST_TYPE: large
  - SNAP_VERSION: latest
    OS: xenial
    TEST_TYPE: large
  - SNAP_VERSION: latest
    OS: centos7
    TEST_TYPE: large
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: SNAP_VERSION=latest OS=alpine TEST_TYPE=large
  - go: 1.6.3
    env: SNAP_VERSION=latest_build OS=alpine TEST_TYPE=large
  - go: 1.6.3
    env: SNAP_VERSION=latest OS=xenial TEST_TYPE=large
  - go: 1.6.3
    env: SNAP_VERSION=latest OS=centos7 TEST_TYPE=large
  - go: 1.6.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
before_deploy:
- "./scripts/pre_deploy.sh"
#deploy:
#- provider: releases
#  api_key:
#    secure: qgJ93IYfJUzPWlsuhvWxczl2H8yyXUsM5rJ6YrNaKUTtwy2bvXg65zEvunEPvs+VbkimlODf42BFyTcb0GqgTx8N13wk8m1K0VFGirDK0KjugQF2zAs61lV1mzkUnTWipVm4a23bPdTt5vncj2kf70RqXBQ3eK75ttnpin47R858H8rl++4JC/wd3vNPZYX2OzahlGmHrsWi1drRGvhngevMqckz2MyUBwCMxhiWFlQSAfCmcD61+zuQ+2RmHN0omJCf59SBiBv+7QaqoVgN2X5EA4HD5hu6J1HpUuMhkWViIbSGhUCqoaH3Cgj2HzWy9WFRW2B18vT+FV5NPgHDZlYwgCCBHBHzp+JImiU1SgLoQJMCwBL8KiOUul7ZjYJLZABFQ/Z/1xhZp5jcy6+CtODGm/xuxNGbo0OE8eMdEs5StVT1wD0EPNAW0c22veksOywr0fW2TITJUfAF+BThRZQF9WGo97+d/8/rSZmhfQe0nfk5L/8P/OSHQn+2b685j5V5CfVqIW7Kq35pDVnwwedyhsjDs+1udQTPjqyT5/PuBjHtB/Fc3xVlDnKrrxn5Igh0o0uCeyLzFkDyjIB2Bn9u7/vBw4QZ5lTKmTaC4TGcwrdpDYDFaxNB0WZFS59NkgitZLHrrqW4XJimvqg7dKatoN3wpzft/csdyNh5tqE=
#  file:
#    - release/snap-plugin-collector-goddd_linux_x86_64
#    - release/snap-plugin-collector-goddd_darwin_x86_64
#  skip_cleanup: true
#  on:
#    repo: swhsiang/snap-plugin-collector-goddd
#    tags: true
#    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
